[[headers]]
  for = "/*"
  [headers.values]
    "Content-Type" = "text/javascript"

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200